version: "3.2"
services:
  api:
    build:
      context: server
      dockerfile: src/api/Dockerfile
    links:
      - db
    ports:
      - "5000:80"
  db:
      image: mysql:5.7
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./server/src/db:/docker-entrypoint-initdb.d/:ro
  processing:
      build:
        context: server
        dockerfile: src/preprocessing/Dockerfile
      links:
        - db
      volumes:
        - ./src/preprocessing/logs:/dataprocessing/logs
  site:
    container_name: site
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development


