version: "3.2"
services:
  api:
    build:
      context: server
      dockerfile: src/api/Dockerfile
    links:
      - db
    ports:
      - "5000:80"
    env_file:
      - ./server/src/common/config/database.docker.env
  db:
      image: mysql:5.7
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./server/src/db:/docker-entrypoint-initdb.d/:ro
  processing:
      build:
        context: server
        dockerfile: src/preprocessing/Dockerfile
      links:
        - db
      volumes:
        - ./server/src/preprocessing/logs:/dataprocessing/logs
      env_file:
        - ./server/src/common/config/database.docker.env
        - ./server/src/common/config/aws.env
  site:
    container_name: site
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - './app:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
  backup:
    image: databack/mysql-backup
    restart: always
    volumes:
      - ./server/src/db/backups:/db
      - ./server/src/db/post-backup:/scripts.d/post-backup
    environment:
      - DB_DUMP_TARGET=/db
      - DB_USER=root
      - DB_PASS=root
      - DB_DUMP_FREQ=1440
      - DB_DUMP_BEGIN=0000
      - DB_SERVER=db