version: "3"
services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    links:
      - db
    ports:
      - "5000:5000"
  db:
      image: mysql:5.7
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./src/db:/docker-entrypoint-initdb.d/:ro
  processing:
      build:
        context: .
        dockerfile: src/preprocessing/Dockerfile
      links:
        - db

