version: "2"
services:
  db:
      image: mysql:5.7
      ports:
        - "3308:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./src/db:/docker-entrypoint-initdb.d/:ro
